import { EstadoTicket, Prioridad } from "../../generated/prisma";

export const ticket = [
  {
    codigo: "INC-2025-0001",
    titulo: "Laptop no enciende",
    descripcion: "El equipo no responde al botón de encendido.",
    estado: EstadoTicket.PENDIENTE,
    prioridad: Prioridad.ALTA,
    solicitanteId: 1,
    categoriaId: 1,
    usuarioAsignadoId: 2,
    fechaLimiteRespuesta: new Date("2025-10-13T12:00:00Z"),
    fechaLimiteResolucion: new Date("2025-10-14T12:00:00Z"),
    respondidoAt: null,
    resueltoAt: null,
    cerradoAt: null,
    cerradoPorId: null,
    cumplioRespuesta: null,
    cumplioResolucion: null,
  },
  {
    codigo: "INC-2025-0002",
    titulo: "Sin acceso a VPN",
    descripcion: "No puedo conectarme a la VPN de la empresa.",
    estado: EstadoTicket.ASIGNADO,
    prioridad: Prioridad.MEDIA,
    solicitanteId: 2,
    categoriaId: 2,
    usuarioAsignadoId: 3,
    fechaLimiteRespuesta: new Date("2025-10-13T10:00:00Z"),
    fechaLimiteResolucion: new Date("2025-10-13T16:00:00Z"),
    respondidoAt: new Date("2025-10-13T10:30:00Z"),
    resueltoAt: null,
    cerradoAt: null,
    cerradoPorId: null,
    cumplioRespuesta: true,
    cumplioResolucion: null,
  },
  {
    codigo: "INC-2025-0003",
    titulo: "Error en sistema de facturación",
    descripcion: "No se puede emitir facturas desde el ERP.",
    estado: EstadoTicket.EN_PROCESO,
    prioridad: Prioridad.URGENTE,
    solicitanteId: 3,
    categoriaId: 4,
    usuarioAsignadoId: 4,
    fechaLimiteRespuesta: new Date("2025-10-13T09:00:00Z"),
    fechaLimiteResolucion: new Date("2025-10-13T21:00:00Z"),
    respondidoAt: new Date("2025-10-13T09:10:00Z"),
    resueltoAt: null,
    cerradoAt: null,
    cerradoPorId: null,
    cumplioRespuesta: true,
    cumplioResolucion: null,
  },
  {
    codigo: "INC-2025-0004",
    titulo: "Problema con impresora",
    descripcion: "La impresora no imprime documentos.",
    estado: EstadoTicket.RESUELTO,
    prioridad: Prioridad.BAJA,
    solicitanteId: 4,
    categoriaId: 1,
    usuarioAsignadoId: 2,
    fechaLimiteRespuesta: new Date("2025-10-14T08:00:00Z"),
    fechaLimiteResolucion: new Date("2025-10-14T18:00:00Z"),
    respondidoAt: new Date("2025-10-14T08:30:00Z"),
    resueltoAt: new Date("2025-10-14T17:00:00Z"),
    cerradoAt: null,
    cerradoPorId: null,
    cumplioRespuesta: true,
    cumplioResolucion: true,
  },
  {
    codigo: "INC-2025-0005",
    titulo: "Restablecimiento de contraseña",
    descripcion: "Solicito restablecer mi contraseña de correo.",
    estado: EstadoTicket.CERRADO,
    prioridad: Prioridad.MEDIA,
    solicitanteId: 5,
    categoriaId: 3,
    usuarioAsignadoId: 3,
    fechaLimiteRespuesta: new Date("2025-10-15T09:00:00Z"),
    fechaLimiteResolucion: new Date("2025-10-15T15:00:00Z"),
    respondidoAt: new Date("2025-10-15T09:10:00Z"),
    resueltoAt: new Date("2025-10-15T14:00:00Z"),
    cerradoAt: new Date("2025-10-15T15:30:00Z"),
    cerradoPorId: 1,
    cumplioRespuesta: true,
    cumplioResolucion: true,
  },
  {
    codigo: "INC-2025-0006",
    titulo: "Problema de red",
    descripcion: "No hay conexión a internet en la oficina.",
    estado: EstadoTicket.PENDIENTE,
    prioridad: Prioridad.URGENTE,
    solicitanteId: 2,
    categoriaId: 2,
    usuarioAsignadoId: 4,
    fechaLimiteRespuesta: new Date("2025-10-16T08:00:00Z"),
    fechaLimiteResolucion: new Date("2025-10-16T14:00:00Z"),
    respondidoAt: null,
    resueltoAt: null,
    cerradoAt: null,
    cerradoPorId: null,
    cumplioRespuesta: null,
    cumplioResolucion: null,
  },
  {
    codigo: "INC-2025-0007",
    titulo: "Actualización de software",
    descripcion: "Solicito actualización de sistema interno.",
    estado: EstadoTicket.ASIGNADO,
    prioridad: Prioridad.BAJA,
    solicitanteId: 3,
    categoriaId: 4,
    usuarioAsignadoId: 2,
    fechaLimiteRespuesta: new Date("2025-10-17T10:00:00Z"),
    fechaLimiteResolucion: new Date("2025-10-17T18:00:00Z"),
    respondidoAt: null,
    resueltoAt: null,
    cerradoAt: null,
    cerradoPorId: null,
    cumplioRespuesta: null,
    cumplioResolucion: null,
  },
];